### ISSUE TITLE
Image of xbox board has "Connector" misspelling

### ISSUE THREAD

**Issue by catogtp** [MakeMHz/makemhz-support#1]
https://github.com/MakeMHz/makemhz-support/blob/main/docs/01-xbox/00-identifying-xbox-revision/images/Xbox-Motherboard-Rev1.jpg

Image has misspelling.

**Comment by LoveMHz** [comment]
Thanks for catching this! Of course, I lost the source file, so I had to recreate the image. It should be all good now.
