### ISSUE TITLE
Dead link to blog on support site

### ISSUE THREAD

**Issue by SebastianHall69** [MakeMHz/makemhz-support#6]
The current link in the top navbar for the blog (Community --> Blog) is https://makemhz.com/blog, but the page doesn't exist. Should the link be https://makemhz.com/blogs/news instead?

https://github.com/MakeMHz/makemhz-support/blob/6562411fded45cc5c83ffb2034bce6ef8664a141/docusaurus.config.js#L122-L127

**Comment by LoveMHz** [comment]
Thank you for catching this! The link has been fixed.
